# Post permalinks
permalink: /:categories/:title.html

# Site wide variables
title: Aberystwyth Live Action Gaming Society

navigation:
- text: About
  url: /
- text: Rules
  url: /rules/
- text: Shootouts
  url: /shootouts/
- text: Events
  url: /events/
- text: Committee
  url: /committee/
